In [1]:
%cd ..

/mnt/data3/haryoaw_workspace/projects/2021/2021_2/new-lm/newlm


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from newlm.lm.elmo.modeling_elmo.elmo_for_classification import ELMOForSequenceClassification, ELMOGPTHeadModel

In [4]:
test = ELMOForSequenceClassification.from_pretrained('../coba/')

Some weights of ELMOForSequenceClassification were not initialized from the model checkpoint at ../coba/ and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [5]:
test_gpt = ELMOGPTHeadModel.from_pretrained('../coba/')

In [6]:
test.elmo.l2r_gpt.transformer.h[0].mlp.c_fc.weight[0,0:5]

tensor([ 0.0403,  0.0151, -0.0017, -0.0265, -0.0128], grad_fn=<SliceBackward>)

In [7]:
test_gpt.l2r_gpt.transformer.h[0].mlp.c_fc.weight[0,0:5]

tensor([ 0.0403,  0.0151, -0.0017, -0.0265, -0.0128], grad_fn=<SliceBackward>)

In [8]:
test.l2r_gpt is test.elmo.l2r_gpt

True

In [9]:
from transformers import GPT2Config

In [10]:
from transformers import GPT2Tokenizer

In [11]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

In [12]:
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

1

In [13]:
tokenizer.pad_token_id

50257

In [14]:
config = GPT2Config(vocab_size=55000, pad_token_id=tokenizer.pad_token_id)

In [15]:
config.pad_token_id

50257

In [ ]:
elmo_model = ELMOForSequenceClassification(config)

In [41]:
batch = tokenizer.batch_encode_plus(['my name is haryo', 'i am a student'], return_tensors='pt', padding=True)

In [43]:
elmo_model(**batch)

> /mnt/data3/haryoaw_workspace/projects/2021/2021_2/new-lm/newlm/newlm/lm/elmo/modeling_elmo/elmo_for_classification.py(70)forward()
     68         breakpoint()
     69 
---> 70         (batch_size, sequence_lengths) = self.elmo.get_sequence_lengths(
     71             input_ids=input_ids, inputs_embeds=inputs_embeds
     72         )



ipdb>  l2r_hidden_states


(tensor([[[-0.0000e+00,  1.1611e-02,  1.7326e-02,  ..., -9.9835e-03,
          -1.6953e-02, -2.4566e-02],
         [ 2.8849e-03,  0.0000e+00, -2.6486e-02,  ..., -3.0950e-02,
           3.7179e-02,  1.2492e-02],
         [ 1.0098e-02, -2.9419e-02, -2.2053e-02,  ..., -4.0406e-02,
          -1.9306e-02, -0.0000e+00],
         [ 0.0000e+00,  4.8221e-03,  0.0000e+00,  ...,  2.3804e-02,
           1.3930e-02, -6.2451e-02],
         [-1.9668e-02, -2.0599e-02,  5.3100e-05,  ..., -1.6212e-03,
           6.4817e-02,  2.9583e-02],
         [ 2.0073e-02, -2.0709e-02,  2.1621e-03,  ..., -0.0000e+00,
           4.3952e-02,  3.1537e-03]],

        [[ 2.4598e-02, -2.9018e-03,  0.0000e+00,  ...,  8.5703e-04,
          -2.2660e-02, -5.1034e-03],
         [ 4.2943e-03,  3.3529e-02, -3.3218e-02,  ...,  2.2429e-03,
           5.3150e-02,  5.4238e-03],
         [-2.4448e-04,  1.1168e-02, -3.9504e-02,  ...,  3.6443e-03,
          -3.9047e-02, -3.4899e-02],
         [-1.0733e-02,  5.9673e-02,  0.0000e+00,  ..

ipdb>  l2r_hidden_states.shape


*** AttributeError: 'tuple' object has no attribute 'shape'


ipdb>  len(l2r_hidden_states)


13


ipdb>  l2r_hidden_states[-1]


tensor([[[ 1.0189,  0.1806, -0.4968,  ...,  2.0206, -0.1706,  0.4485],
         [ 1.4900,  1.5461, -0.2642,  ...,  1.7416, -0.6277,  0.9480],
         [ 1.5361,  1.0794, -0.7854,  ...,  0.8813, -0.6498,  0.5877],
         [-0.6881,  1.8265,  0.1203,  ...,  1.2942,  0.7702,  1.0941],
         [ 0.5785,  0.4507,  0.1624,  ...,  0.6647,  0.5696,  0.1413],
         [ 0.2623,  0.4321, -0.9669,  ...,  0.9605, -1.1859,  1.1806]],

        [[-0.5746, -0.7328, -0.6882,  ...,  1.4852, -0.6503,  1.2086],
         [ 1.2129,  0.6043,  0.9683,  ...,  1.7246,  0.0382,  2.1915],
         [ 0.8946,  0.4062,  0.8943,  ...,  1.7583,  0.5385,  0.7861],
         [ 1.2371, -0.0184,  1.4376,  ...,  0.8612,  0.0528,  1.6469],
         [ 1.0251, -0.1251,  0.5580,  ...,  1.4267, -0.3987,  1.1045],
         [ 1.5943, -0.0750,  0.0051,  ...,  2.1563,  0.2468,  2.3820]]],
       grad_fn=<ViewBackward>)


ipdb>  l2r_hidden_states[-1].shape


torch.Size([2, 6, 768])


ipdb>  q


BdbQuit: 